- name: Install and configure Jupyter
  hosts:
    - localhost
  gather_facts: false
  tasks:
    - name: Install CDO
      become: yes
      apt:
        name: "{{ packages }}"
        allow_unauthenticated: true
      vars:
        packages:
          - cdo

    - name: Download Miniconda
      get_url:
        url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        dest: /tmp/install-miniconda.sh
        mode: 0550

    - name: Create conda folder
      become: True
      file:
        path: /opt/miniconda3
        state: directory
        owner: ubuntu
        mode: 755
        recurse: yes

    - name: Run the installer
      shell: /tmp/install-miniconda.sh -b -u -p /opt/miniconda3

    - name: Remove the installer
      file:
        state: absent
        path: /tmp/install-miniconda.sh

    - name: Add miniconda bin to path
      become: True
      shell: echo 'export PATH=/opt/miniconda3/bin:$PATH' >> /etc/profile

    - name: conda - read permission for all
      become: True
      file:
        path: /opt/miniconda3
        mode: +r
        recurse: yes

    - name: conda - execution permission for all
      become: True
      file:
        path: /opt/miniconda3/bin
        mode: +x
        recurse: yes
